HOPS = 3
BATCH_SIZE = 64
EMBEDDING_SIZE = 300
MULTILABEL = 0
TOP_K = 20
LSTM = 0
N_LAYER = 3
FIX_VOCAB = 1
CUDA_DEVICE = "0"
CANDIDATE_POOL = 4000
MAX_MEMORY_SIZE = 20
TOKENIZE_CHAR = 0

# do not delete
# HOPS = 2
# BATCH_SIZE = 64
# EMBEDDING_SIZE = 300
# MULTILABEL = 0
# TOP_K = 20
# LSTM = 0
# N_LAYER = 3
# FIX_VOCAB = 0
# CUDA_DEVICE = "0"
# CANDIDATE_POOL = 300
# MAX_MEMORY_SIZE=20
# TOKENIZE_CHAR=1
